//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredients
    {
        public int id { get; set; }
        public int recipeId { get; set; }
        public int productId { get; set; }
        public double amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
